### ISSUE TITLE
when using multiple autoprereqs dist modules are not skipped

### ISSUE THREAD

**Issue by carandraug** [rjbs/Dist-Zilla#729]
I'm using two `[AutoPrereqs]`, each with their own `[FileFinder]` because I want two subsets of files to be handled different. I have found that in this case, requirements that the modules have of other modules in the same dist are not ignored.

I'm using Dist-Zilla-6.032

Here's a minimal example:

```
mkdir lib

cat <<EOF > dist.ini 
name    = A
abstract = abstract
author  = E. Xavier Ample <example@cpan.org>
license = Perl_5
copyright_holder = E. Xavier Ample <example@cpan.org>
version = 0.001

[@Basic]

[FileFinder::ByName / A_Finder]
match = ^lib/A.pm$

[FileFinder::ByName / B_Finder]
match = ^lib/B.pm$

[AutoPrereqs / A_Prereqs]
finder = A_Finder

[AutoPrereqs / B_Prereqs]
finder = B_Finder
EOF

cat <<EOF > lib/A.pm
package A;
use Y;
1;
EOF

cat <<EOF > lib/B.pm
package B;
use A;
use Z;
1;
EOF

dzil build
```

The built distribution has this `META.yml`:

```
---
abstract: abstract
author:
  - 'E. Xavier Ample <example@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: A
requires:
  A: '0'
  Y: '0'
  Z: '0'
version: '0.001'
x_generated_by_perl: v5.40.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
```

Note the declared requirement on the module `A` which is part of the distribution itself.
